# -*- coding: utf-8 -*-
"""
Created on Mon Feb 18 08:05:47 2019

@author: Med Said M'bareck
"""
###ABCDEFGHIJKLMNOPQRSTUVWXYZ##
a="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
b="BCDEFGHIJKLMNOPQRSTUVWXYZA"
c="CDEFGHIJKLMNOPQRSTUVWXYZAB"
d="DEFGHIJKLMNOPQRSTUVWXYZABC"
e="EFGHIJKLMNOPQRSTUVWXYZABCD"
f="FGHIJKLMNOPQRSTUVWXYZABCDE"
g="GHIJKLMNOPQRSTUVWXYZABCDEF"
h="HIJKLMNOPQRSTUVWXYZABCDEFG"
i="IJKLMNOPQRSTUVWXYZABCDEFGH"
j="JKLMNOPQRSTUVWXYZABCDEFGHI"
k="KLMNOPQRSTUVWXYZABCDEFGHIJ"
l="LMNOPQRSTUVWXYZABCDEFGHIJK"
m="MNOPQRSTUVWXYZABCDEFGHIJKL"
n="NOPQRSTUVWXYZABCDEFGHIJKLM"
o="OPQRSTUVWXYZABCDEFGHIJKLMN"
p="PQRSTUVWXYZABCDEFGHIJKLMNO"
q="QRSTUVWXYZABCDEFGHIJKLMNOP"
r="RSTUVWXYZABCDEFGHIJKLMNOPQ"
s="STUVWXYZABCDEFGHIJKLMNOPQR"
t="TUVWXYZABCDEFGHIJKLMNOPQRS"
u="UVWXYZABCDEFGHIJKLMNOPQRST"
v="VWXYZABCDEFGHIJKLMNOPQRSTU"
w="WXYZABCDEFGHIJKLMNOPQRSTUV"
x="XYZABCDEFGHIJKLMNOPQRSTUVW"
y="YZABCDEFGHIJKLMNOPQRSTUVWX"
z="ZABCDEFGHIJKLMNOPQRSTUVWXY"



def getFirstCoupleAndDeleteThemFromTextAndKey(text ,cle):
    t = text[0]
    c = cle[0]
    text = text.replace(text[0],"")
    cle = cle.replace(cle[0],"")   
    return t,c


    
print(getFirstCoupleAndDeleteThemFromTextAndKey("med","sidi"))
    

#def vigenere(text,cle):
#    cryptedText = ""
 
#   for lettre in text:

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
